name: Pull Request

on: pull_request

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
          - name: Get repo
            uses: actions/checkout@v2
          - name: Install Node
            uses: actions/setup-node@v2
            with:
              node-version: '14'
              cache: 'npm'

        - name: Install truffle
          run: npm install -g truffle
        
        - name: Install application dependencies
          run: npm i

        - name: Run unit tests of contracts
          run: truffle test
            

